language: node_js

node_js:
  - '10'

script:
  - npm ci
  - "grep -qF lastUpdatedTstamp node_modules/@vuepress/plugin-last-updated/index.js && patch --batch node_modules/@vuepress/plugin-last-updated/index.js last-updated.patch || true"
  - "grep -qF lastUpdatedTstamp node_modules/vuepress-plugin-sitemap/index.js && patch --batch node_modules/vuepress-plugin-sitemap/index.js sitemap.patch || true"
  - npm run build
  - npm run check

addons:
  ssh_known_hosts: asksinpp.de:22024

before_deploy:
  - echo -e "$DEPLOY_KEY" > /tmp/deploy_key
  - chmod 600 /tmp/deploy_key

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -a --delete-after -e "ssh -p 22024 -i /tmp/deploy_key" .vuepress/dist/* www@asksinpp.de:/asksinpp.de
    on:
      branch: master
