language: node_js

node_js:
  - '10'

branches:
  only:
    - dev

script:
  - npm ci
  - npm run build
#  - npm run check

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ".vuepress/dist"
  github-token: "$GITHUB_TOKEN"
  target-branch: gh-pages
  on:
    branch: dev
