language: node_js

node_js:
  - '10'

branches:
  only:
    - master

script:
  - npm ci
  - "grep -qF 'compiler: vue_template_compiler_1.default' node_modules/@vuepress/shared-utils/lib/parseVueFrontmatter.js && patch --batch node_modules/@vuepress/shared-utils/lib/parseVueFrontmatter.js shared-utils.patch || true"
  - npm run build
  - npm run check

cache:
  directories:
    - node_modules

#deploy:
#  provider: pages
#  skip-cleanup: true
#  local_dir: ".vuepress/dist"
#  github-token: "$GITHUB_TOKEN"
#  target-branch: gh-pages
#  on:
#    branch: master
