on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      # GIT Checkout
      - uses: actions/checkout@v2

      # Cache node_modules
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Setup Node.JS
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Build
      - run: npm ci
      - run: npm run build

      # Deploy
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          publish_dir: .vuepress/dist/
          deploy_key: ${{ secrets.GH_PAGES_DEPLO_KEY }}
          external_repository: AskSinPP/asksinpp.github.io
