on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      # GIT Checkout
      - uses: actions/checkout@v2

      # Cache node_modules
      - uses: actions/cache@v2.1.3
        with:
          path: node_modules

      # Setup Node.JS
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Build
      - run: npm ci
      - run: npm run build

      # Deploy
      - uses: burnett01/rsync-deployments@4.1
        if: github.ref == 'refs/heads/master'
        with:
          switches: -avzr --delete
          path: .vuepress/dist/
          remote_path: /asksinpp.de
          remote_host: asksinpp.de
          remote_port: 22022
          remote_user: www
          remote_key: ${{ secrets.DEPLOY_KEY }}

